### PR TITLE
CI against rails 5.1

### PR DESCRIPTION
**Pull request by sue445**

### CODE REVIEW

**Comment by sue445** [comment]
@mitaku I think this PR is failed 😢 

I fixed at 867d25dce4384dd3feeb585dc046aeb2d224fb9f . Please merge #21 first 🙏

**Comment by sue445** [comment]
@mitaku I rebased and removed WIP. Please review 🙇

**Comment by mitaku** [comment]
Thank you for pull request ✨

**Comment by sue445** [comment]
😄

**Pull request merged**
